### ISSUE TITLE
谷歌云

### ISSUE THREAD

**Issue by Surile** [raoenhui/awsSetup#1]
`真是薅的一手羊毛`

`谷歌云`也可以免费搭建、

`搬瓦工`和`Vultr`其实也是可以的，不过服务器收费。

**Comment by raoenhui** [comment]
等aws要到期了，可以试试谷歌云，谷歌云免费的多久过期

**Comment by Surile** [comment]
新用户增送300美金优惠券，不过好像也是需要绑定信用卡。具体能用多久还真不知道

**Comment by raoenhui** [comment]
Great!
