### ISSUE TITLE
AWS EC2 连接的问题

### ISSUE THREAD

**Issue by zzkzzk1996** [raoenhui/awsSetup#3]
用ssh连接EC2的时候出现"Connection closed by *** "的问题，查找了半天也没找到解决方案，求教。

**Comment by raoenhui** [comment]
cd /etc/ssh && sudo chmod -R 777 * 试试？

**Comment by zzkzzk1996** [comment]
> cd /etc/ssh && sudo chmod -R 777 * 试试？

查过了，不是权限的问题。具体是什么问题我也没搞明白，但是我把EC2的instance删除后并且将地区从us-east-1切换到us-west-1再重新lauch instance就解决了。
